# Generated by Django 4.2.4 on 2023-11-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepaths',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.movies'),
        ),
        migrations.AlterField(
            model_name='imagepaths',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.imagetypes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='movies.people'),
        ),
    ]
