# Generated by Django 4.2.4 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_genrelikes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrelikes',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keywordlikes',
            name='point',
            field=models.IntegerField(),
        ),
    ]
