# Generated by Django 4.2.4 on 2023-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_genrelikes_point_alter_keywordlikes_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrelikes',
            name='point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keywordlikes',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
